apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    helm.toolkit.fluxcd.io/name: ww-gitops
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: allow-dashboard-ingress
spec:
  ingress:
  - ports:
    - port: 9001
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: ww-gitops
      app.kubernetes.io/name: weave-gitops
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    helm.toolkit.fluxcd.io/name: ww-gitops
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: allow-dashboard-egress
spec:
  egress:
  - {}
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: ww-gitops
      app.kubernetes.io/name: weave-gitops
  policyTypes:
  - Egress
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ww-gitops
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/version: v0.38.0
    helm.sh/chart: weave-gitops-4.0.36
    helm.toolkit.fluxcd.io/name: ww-gitops
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: weave-gitops
---
apiVersion: v1
data:
  password: JDJhJDEwJE83ZEZVVXd5WHdHQkFMYk9wOWl4NGVTdEV5Y3ZQWVZzbTM4TlBCQm10ejl5cWxITG5LT25T
  username: YWRtaW4=
kind: Secret
metadata:
  labels:
    helm.toolkit.fluxcd.io/name: ww-gitops
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: cluster-user-auth
  namespace: flux-system
type: Opaque
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    helm.toolkit.fluxcd.io/name: ww-gitops
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: wego-admin-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - buckets
  - helmcharts
  - gitrepositories
  - helmrepositories
  - ocirepositories
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - notification.toolkit.fluxcd.io
  resources:
  - providers
  - alerts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.contrib.fluxcd.io
  resources:
  - terraforms
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
- apiGroups:
  - notification.toolkit.fluxcd.io
  resources:
  - providers
  - alerts
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - image.toolkit.fluxcd.io
  resources:
  - imagepolicies
  - imagerepositories
  - imageupdateautomations
  verbs:
  - get
  - list
  - watch
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    helm.toolkit.fluxcd.io/name: ww-gitops
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: weave-gitops
rules:
- apiGroups:
  - ""
  resources:
  - users
  - groups
  verbs:
  - impersonate
- apiGroups:
  - ""
  resourceNames:
  - cluster-user-auth
  - oidc-auth
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    helm.toolkit.fluxcd.io/name: ww-gitops
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: admin-user-read-resources-cr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wego-admin-cluster-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: ww-gitops
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/version: v0.38.0
    helm.sh/chart: weave-gitops-4.0.36
    helm.toolkit.fluxcd.io/name: ww-gitops
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: weave-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: weave-gitops
subjects:
- kind: ServiceAccount
  name: weave-gitops
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    helm.toolkit.fluxcd.io/name: ww-gitops
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: wego-admin-role
  namespace: flux-system
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - buckets
  - helmcharts
  - gitrepositories
  - helmrepositories
  - ocirepositories
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - notification.toolkit.fluxcd.io
  resources:
  - providers
  - alerts
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - infra.contrib.fluxcd.io
  resources:
  - terraforms
  verbs:
  - get
  - list
  - watch
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    helm.toolkit.fluxcd.io/name: ww-gitops
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: admin-user-read-resources
  namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wego-admin-role
subjects:
- kind: User
  name: wego-admin
  namespace: flux-system
---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: ww-gitops
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/version: v0.38.0
    helm.sh/chart: weave-gitops-4.0.36
    helm.toolkit.fluxcd.io/name: ww-gitops
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: weave-gitops
spec:
  ports:
  - name: http
    port: 9001
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: ww-gitops
    app.kubernetes.io/name: weave-gitops
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: ww-gitops
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/part-of: weave-gitops
    app.kubernetes.io/version: v0.38.0
    helm.sh/chart: weave-gitops-4.0.36
    helm.toolkit.fluxcd.io/name: ww-gitops
    helm.toolkit.fluxcd.io/namespace: flux-system
    weave.works/app: weave-gitops-oss
  name: weave-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ww-gitops
      app.kubernetes.io/name: weave-gitops
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ww-gitops
        app.kubernetes.io/name: weave-gitops
        app.kubernetes.io/part-of: weave-gitops
        weave.works/app: weave-gitops-oss
    spec:
      containers:
      - args:
        - --log-level
        - info
        - --insecure
        - --route-prefix=/weave-gitops
        env:
        - name: WEAVE_GITOPS_FEATURE_TENANCY
          value: "true"
        - name: WEAVE_GITOPS_FEATURE_CLUSTER
          value: "false"
        image: ghcr.io/weaveworks/wego-app:v0.38.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: http
        name: weave-gitops
        ports:
        - containerPort: 9001
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: weave-gitops
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: ww-gitops
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/version: v0.38.0
    helm.sh/chart: weave-gitops-4.0.36
    helm.toolkit.fluxcd.io/name: ww-gitops
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: weave-gitops
spec:
  ingressClassName: nginx
  rules:
  - host: www.private-cloud.com
    http:
      paths:
      - backend:
          service:
            name: weave-gitops
            port:
              number: 9001
        path: /weave-gitops
        pathType: Prefix
