apiVersion: repo-manager.pulpproject.org/v1beta2
kind: Pulp
metadata:
  name: pulp
  namespace: awx
spec:
  api:
    replicas: 1
  content:
    replicas: 1
  worker:
    replicas: 1
  web:
    replicas: 1
  cache:
    enabled: true
    redis_storage_class: standard
  # pulp_settings:
  #   api_root: "/pulp/"
