---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/kube-prometheus
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
  timeout: 3m0s
  wait: true
  dependsOn:
    - name: ingress-nginx
      namespace: flux-system
