---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kube-prometheus/manifests
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: kubernetes-apps
  targetNamespace: monitoring
  timeout: 3m0s
  wait: true
