---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: awx
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./awx
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: apps
  targetNamespace: awx
  timeout: 3m0s
  wait: true
