---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/metrics-server
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: apps
  targetNamespace: kube-system
  timeout: 3m0s
  wait: true
