---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argocd
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/argocd
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
  targetNamespace: argocd
  timeout: 3m0s
  wait: true
  dependsOn:
    - name: ingress-nginx
      namespace: flux-system
