---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./ingress-nginx
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: kubernetes-apps
  targetNamespace: ingress-nginx
  timeout: 3m0s
  wait: true
