---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
  targetNamespace: ingress-nginx
  timeout: 3m0s
  wait: true
