apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  admin_user: admin
  admin_password_secret: awx-admin-password
  service_type: clusterip
  ingress_type: ingress
  ingress_path: /awx
  projects_storage_size: 1Gi
  ingress_annotations: |
    kubernetes.io/ingress.class: nginx
  hostname: www.private-cloud.com
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-admin-password
  namespace: awx
stringData:
  password: admin
