---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: olm
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/olm
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
  targetNamespace: olm
  timeout: 3m0s
  wait: true
