name: e2e test

on:  # yamllint disable-line rule:truthy
  - push
  - pull_request

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    - name: run e2e test
      env:
        GITHUB_USER: ${{ secrets.FLUX_USER }}
        GITHUB_TOKEN: ${{ secrets.FLUX_TOKEN }}
      run: bash test/e2e-test.sh
