name: e2e test

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - 'release-*'
  pull_request:
    branches:
      - 'release-*'

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install k8s cluster and deploy flux to install all apps
      env:
        GITHUB_USER: ${{ secrets.FLUX_USER }}
        GITHUB_TOKEN: ${{ secrets.FLUX_TOKEN }}
      run: bash ./install.sh

    - name: Run deployment test
      run: bash ./test/deployment-test.sh

    - name: Run ingress test
      run: bash ./test/ingress-test.sh
